Repository akeneo/pim-api-docs, pull requests merged in 2022-10, with the labels that each got.

#666 OCT-154: fix broken link in API docs
  content/apps/authentication-and-authorization.md
Labels: echoes/intent: technical

#662 PIM-10655: Fix completeness format in product endpoints
  content/swagger/akeneo-web-api.json
  content/swagger/resources/products/definitions/examples/products.yaml
  content/swagger/resources/products/definitions/product.yaml
  content/swagger/resources/products_uuid/definitions/examples/products_uuid.yaml
  content/swagger/resources/products_uuid/definitions/product_uuid.yaml
Labels: echoes/intent: maintenance

#672 CPM-736 : Add 422 error code on "Update/create several products"
  content/swagger/akeneo-web-api.json
  content/swagger/resources/products_uuid/routes/products_uuid.yaml
Labels: echoes/intent: feature

#668 fix(API-1867): update catalogs doc + update postman api export
  content/files/Akeneo PIM API.postman_collection.json
  content/swagger/akeneo-web-api.json
  content/swagger/resources/app_catalogs/routes/app_catalogs.yaml
  content/swagger/resources/app_catalogs/routes/app_catalogs_id.yaml
  content/swagger/resources/app_catalogs/routes/app_catalogs_id_product_uuids.yaml
  src/api-reference/reference.handlebars
  tasks/reference.js
Labels: echoes/intent: feature

#667 fix(API-1852): Update API rest pagination offset section
  content/rest-api/pagination.md
Labels: echoes/intent: maintenance

#675 API-1893: Add guided tutorial "How to retrieve PIM structure"
  components/components.css
  components/components.html
  content/apps/how-to-retrieve-pim-structure.md
  content/getting-started/synchronize-pim-products-6x/step-1.md
  content/img/icons/icon--arrow-back.svg
  content/img/icons/icon--unselect-tag.svg
  styles/guided-tutorial.less
  styles/variables.less
  tasks/build-doc.js
Labels: echoes/intent: feature

#676 feat(API-1895): create 'how to get app token' page
  content/apps/apps-how-to-get-your-app-token.md
  content/apps/create-app/activate-php.md
  content/apps/create-app/callback-php.md
  content/apps/how-to-retrieve-pim-structure.md
  content/apps/old/apps-getting-started.md
  content/apps/overview.md
  content/img/apps/test-app-creation-credentials.png
  content/img/apps/test-app-creation-info.png
  src/api-reference/reference.handlebars
  src/index.handlebars
  tasks/build-doc.js
Labels: echoes/intent: feature
