Repository akeneo/pim-api-docs, pull requests merged in 2022-09, with the labels that each got.

#640 API-1864: Clean API Client available version tags
  content/php-client/resources/PAM/asset-categories.md
  content/php-client/resources/PAM/asset-reference-files.md
  content/php-client/resources/PAM/asset-tags.md
  content/php-client/resources/PAM/asset-variation-files.md
  content/php-client/resources/PAM/assets.md
  content/php-client/resources/app-catalog/app-catalog-product.md
  content/php-client/resources/app-catalog/app-catalog.md
  content/php-client/resources/asset-manager/asset-attribute-options.md
  content/php-client/resources/asset-manager/asset-attributes.md
  content/php-client/resources/asset-manager/asset-families.md
  content/php-client/resources/asset-manager/asset-media-files.md
  content/php-client/resources/asset-manager/assets.md
  content/php-client/resources/catalog-structure/association-types.md
  content/php-client/resources/catalog-structure/attribute-groups.md
  content/php-client/resources/catalog-structure/attribute-options.md
  content/php-client/resources/catalog-structure/attributes.md
  content/php-client/resources/catalog-structure/categories.md
  content/php-client/resources/catalog-structure/families.md
  content/php-client/resources/catalog-structure/family-variants.md
  content/php-client/resources/products/product-drafts.md
  content/php-client/resources/products/product-media-files.md
  content/php-client/resources/products/product-model-drafts.md
  content/php-client/resources/products/product-models.md
  content/php-client/resources/products/products.md
  content/php-client/resources/products/published-products.md
  content/php-client/resources/reference-entity/attribute-options.md
  content/php-client/resources/reference-entity/attributes.md
  content/php-client/resources/reference-entity/media-files.md
  content/php-client/resources/reference-entity/records.md
  content/php-client/resources/reference-entity/reference-entities.md
  content/php-client/resources/target-market-settings/channels.md
  content/php-client/resources/target-market-settings/currencies.md
  content/php-client/resources/target-market-settings/locales.md
  content/php-client/resources/target-market-settings/measure-families.md
  content/php-client/resources/target-market-settings/measurement-families.md
  tasks/build-doc.js
Labels: echoes/effort: M, echoes/intent: feature

#656 CXP-1300: add first mapping
  content/mapping/product/0.0.1/schema
  tasks/copy-assets.js
Labels: echoes/intent: feature

#624 [On Hold] API-1836: Write a doc "From identifiers to UUID" for partners
  content/getting-started/from-identifiers-to-uuid-7x/welcome.md
  content/swagger/akeneo-web-api.json
  src/guides-index.handlebars
  tasks/build-doc.js
Labels: echoes/effort: M, echoes/intent: feature

#645 PHP client product UUID update
  content/php-client/exception.md
  content/php-client/getting-started.md
  content/php-client/list-resources.md
  content/php-client/resources/products/product-drafts-uuid.md
  content/php-client/resources/products/products-uuid.md
  tasks/build-doc.js
Labels: echoes/effort: S, echoes/intent: feature
