Repository akeneo/pim-api-docs, pull requests merged in 2022-08, with the labels that each got.

#626 Quick start apps
  content/apps/apps-getting-started.md
  content/apps/authentication-and-authorization.md
  content/apps/catalogs.md
  content/apps/overview.md
  content/img/apps/pim-marketplace-with-apps.png
  src/partials/layout.handlebars
  tasks/build-doc.js
Labels: echoes/effort: M, echoes/intent: feature

#636 API-1803 & API-1804: Filter Asset & Reference Entity by codes
  content/files/Akeneo PIM API.postman_collection.json
  content/rest-api/filter.md
Labels: echoes/intent: feature

#644 API-1844: Add Create a sandbox request button
  content/img/icons/sandbox.svg
  src/index.handlebars
Labels: echoes/effort: S, echoes/intent: feature

#638 [On Hold] - API-1859: PHP client Catalog update
  content/php-client/resources/app-catalog/app-catalog-product.md
  content/php-client/resources/app-catalog/app-catalog.md
  tasks/build-doc.js
Labels: echoes/intent: feature
