Repository akeneo/pim-api-docs, pull requests merged in 2023-11, with the labels that each got.

#846 CPM-1209: Published Product Deprecated
  content/concepts/products.md
  content/php-client/resources/products/published-products.md
  src/api-reference/index.handlebars
  src/api-reference/reference.handlebars
  styles/alert.less
  tasks/reference.js
Labels: echoes/intent: feature, echoes/effort: S

#853 CPM-1318: Add with_attribute_options__product_models
  content/swagger/akeneo-web-api.json
  content/swagger/parameters.yaml
  content/swagger/resources/product_models/definitions/product_model.yaml
  content/swagger/resources/product_models/routes/product_models.yaml
Labels: echoes/intent: feature, echoes/effort: XS

#855 CXP-1660: Added new meta-schema versions to catalogs
  content/mapping/product/0.1.0/schema
  content/mapping/product/0.2.0/schema
Labels: echoes/intent: feature

#856 CXP-1639: add mapping meta-schema v0.3.0
  content/mapping/product/0.3.0/schema
Labels: echoes/intent: feature, octopus
