Repository akeneo/pim-api-docs, pull requests merged in 2023-01, with the labels that each got.

#733 feat(api-1973): add 'deployments' folder along with its CI/CD integration
  .circleci/config.yml
  deployments/modules/dependencies/apis.tf
  deployments/modules/dependencies/artifact-registry.tf
  deployments/modules/dependencies/dns.tf
  deployments/modules/dependencies/monitoring.tf
  deployments/modules/dependencies/variables.tf
  deployments/modules/services/main.tf
  deployments/modules/services/networking/backend-bucket.tf
  deployments/modules/services/networking/dns.tf
  deployments/modules/services/networking/load-balancer.tf
  deployments/modules/services/networking/locals.tf
  deployments/modules/services/networking/outputs.tf
  deployments/modules/services/networking/variables.tf
  deployments/modules/services/outputs.tf
  deployments/modules/services/storage/main.tf
  deployments/modules/services/storage/outputs.tf
  deployments/modules/services/storage/variables.tf
  deployments/modules/services/variables.tf
  deployments/stages/dev/dependencies/main.tf
  deployments/stages/dev/dependencies/variables.tf
  deployments/stages/dev/services/main.tf
  deployments/stages/dev/services/outputs.tf
  deployments/stages/dev/services/providers.tf
  deployments/stages/dev/services/variables.tf
  deployments/stages/ppd/dependencies/main.tf
  deployments/stages/ppd/dependencies/variables.tf
  deployments/stages/ppd/services/main.tf
  deployments/stages/ppd/services/outputs.tf
  deployments/stages/ppd/services/providers.tf
  deployments/stages/ppd/services/variables.tf
  deployments/stages/prd/dependencies/main.tf
  deployments/stages/prd/dependencies/variables.tf
  deployments/stages/prd/services/main.tf
  deployments/stages/prd/services/outputs.tf
  deployments/stages/prd/services/providers.tf
  deployments/stages/prd/services/variables.tf
  deployments/stages/sdx/dependencies/main.tf
  deployments/stages/sdx/dependencies/variables.tf
  deployments/stages/sdx/services/main.tf
  deployments/stages/sdx/services/outputs.tf
  deployments/stages/sdx/services/providers.tf
  deployments/stages/sdx/services/variables.tf
Labels: echoes/intent: technical, wip

#739 API-2008: Add new 'How to get PIM category tree' guided tutorial
  content/tutorials/guides/how-to-collect-product-variations.md
  content/tutorials/guides/how-to-get-pim-category-tree.md
  src/partials/layout.handlebars
  tasks/build-doc.js
Labels: echoes/intent: feature

#743 API-1969: 'Develop your App' button vertical alignment
  components/components.css
  styles/guided-tutorial.less
Labels: echoes/intent: feature

#742 feat(API-1904): Add JS code snippets for GT "How to collect product variations"
  content/tutorials/guides/how-to-collect-product-variations.md
  content/tutorials/guides/how-to-get-families-and-attributes.md
Labels: echoes/intent: feature

#750 feat(ODX-1): update snippets theme for guided tutorial
  content/swagger/akeneo-web-api.json
  package-lock.json
  package.json
  src/partials/guided-tutorials.handlebars
  src/partials/layout.handlebars
  styles/guided-tutorial.less
  tasks/build-doc.js
  tasks/copy-assets.js
  yarn.lock
Labels: echoes/intent: feature

#747 feat(API-2012): refator boucle + somes request + save method in guided tutorials JS snippet
  content/apps/create-app/callback-php.md
  content/tutorials/guides/how-to-collect-product-variations.md
  content/tutorials/guides/how-to-get-families-and-attributes.md
  content/tutorials/guides/how-to-get-pim-category-tree.md
  content/tutorials/guides/how-to-get-pim-product-information.md
  content/tutorials/guides/how-to-get-your-app-token.md
  content/tutorials/guides/how-to-retrieve-pim-structure.md
Labels: echoes/intent: maintenance
