Repository akeneo/pim-api-docs, pull requests merged in 2023-03, with the labels that each got.

#770 feat(ODX-15): integrate the new UI for app developer tools
  components/components.html
  components/tile-app.css
  components/tile-app.html
  content/apps/app-developer-tools.md
  content/img/apps/dev-tools-akeneo.svg
  content/img/apps/dev-tools-download.svg
  content/img/apps/dev-tools-langages.svg
  content/img/apps/dev-tools-php.svg
  content/img/apps/dev-tools-postman.svg
  content/img/apps/dev-tools-slack.svg
  gulpfile.js
  src/partials/apps-developer-tools.handlebars
  styles/apps-developer-tools.less
  styles/variables.less
  tasks/build-doc.js
Labels: echoes/intent: feature

#783 Sample apps deployment
  components/block-create-app.css
  components/block-create-app.html
  components/components.html
  components/tile-app.css
  components/tile-app.html
  content/apps/app-developer-tools.md
  content/apps/certify-your-app.md
  content/apps/homepage.md
  content/apps/publish-your-app.md
  content/img/apps/dev-tools-akeneo.svg
  content/img/apps/dev-tools-download.svg
  content/img/apps/dev-tools-langages.svg
  content/img/apps/dev-tools-php.svg
  content/img/apps/dev-tools-postman.svg
  content/img/apps/dev-tools-slack.svg
  content/img/apps/julia.png
  content/img/apps/peter.png
  content/news/2023.md
  gulpfile.js
  src/partials/apps-developer-tools.handlebars
  src/partials/layout.handlebars
  styles/apps-developer-tools.less
  styles/variables.less
  tasks/build-doc.js
Labels: echoes/intent: feature

#784 Update link to add sample apps
  content/apps/authentication-and-authorization.md
Labels: echoes/intent: feature

#756 ODX-10 : Rework the "Get your app token " tutorial
  Makefile
  content/img/apps/app-ngrok-result.png
  content/img/apps/connected-test-app.png
  content/img/apps/marketplace-with-test-app.png
  content/img/apps/test-app-creation-info.png
  content/tutorials/guides/how-to-get-your-app-token.md
Labels: echoes/intent: feature

#778 CXP-1409: JSON Meta Schema V0.0.11
  content/mapping/product/0.0.11/schema
Labels: echoes/intent: feature, octopus

#776 CXP-1389: JSON Meta Schema V0.0.10
  content/mapping/product/0.0.10/schema
Labels: echoes/intent: feature, octopus

#791 CXP-1414: JSON Meta Schema V0.0.12
  content/mapping/product/0.0.12/schema
Labels: echoes/intent: feature

#800 OCT-233: Document email_verified claim for JWT token
  content/apps/authentication-and-authorization.md
Labels: echoes/intent: technical

#808 Add Asset date attribute type in the table of content of the attributes section
  content/concepts/asset-manager.md
Labels: salamander
