Repository akeneo/pim-api-docs, pull requests merged in 2023-02, with the labels that each got.

#738 feat(api-2010): add 'destroy' jobs
  .circleci/config.yml
  .circleci/tools/destroyer/__init__.py
  .circleci/tools/destroyer/config.yml
  .circleci/tools/destroyer/get_outdated_environment.py
  .circleci/tools/destroyer/remove_state_folder.py
  .circleci/tools/destroyer/settings.py
  .circleci/tools/destroyer/terraform_destroy.py
  .circleci/tools/requirements.txt
Labels: echoes/intent: technical, echoes/effort: S

#758 feat(odx-23): add 'master' workflow
  .circleci/config.yml
  deployments/modules/services/networking/locals.tf
  deployments/modules/services/variables.tf
  deployments/stages/dev/services/variables.tf
  deployments/stages/prd/dependencies/variables.tf
  deployments/stages/prd/services/main.tf
  deployments/stages/sdx/services/variables.tf
Labels: echoes/intent: technical, echoes/effort: S

#741 CXP-1287: JSON Meta Schema V0.0.3
  content/mapping/product/0.0.3/schema
Labels: echoes/intent: feature, octopus

#748 CXP-1375: JSON Meta Schema V0.0.4
  content/mapping/product/0.0.4/schema
Labels: echoes/intent: feature, octopus

#762 CXP-1390: JSON Meta schema v0.0.5
  content/mapping/product/0.0.5/schema
Labels: echoes/intent: feature, octopus

#757 CXP-1379: JSON Meta Schema V0.0.6
  content/mapping/product/0.0.6/schema
Labels: echoes/intent: feature, octopus

#771 CXP-1392: JSON Meta Schema V0.0.7
  content/mapping/product/0.0.7/schema
Labels: echoes/intent: feature, octopus

#772 CXP-1393: JSON Meta Schema V0.0.8
  content/mapping/product/0.0.8/schema
Labels: echoes/intent: feature, octopus

#774 CXP-1396: JSON Meta Schema V0.0.9
  content/mapping/product/0.0.9/schema
Labels: echoes/intent: feature, octopus

#699 GRF-446: Update the API documentation with the with_enriched_values parameter
  content/swagger/akeneo-web-api.json
  content/swagger/parameters.yaml
  content/swagger/resources/categories/definitions/category.yaml
  content/swagger/resources/categories/routes/categories.yaml
  content/swagger/resources/categories/routes/categories_code.yaml
Labels: echoes/intent: feature

#781 GRF-760: update enriched categories endpoints
  content/swagger/akeneo-web-api.json
  content/swagger/parameters.yaml
  content/swagger/paths.yaml
  content/swagger/resources/categories/routes/categories_code.yaml
  content/swagger/resources/categories/routes/category_media_files_code_download.yaml
Labels: echoes/intent: feature
